-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT(USER_INFO.USER_ID)) 'PURCHASED_USERS',
    ROUND(COUNT(DISTINCT(USER_INFO.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) , 1) 'PUCHASED_RATIO'
FROM USER_INFO INNER JOIN ONLINE_SALE  
   ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH