-- 코드를 입력하세요
SELECT APPOINTMENT.APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, 
       DR_NAME, APPOINTMENT.APNT_YMD
FROM APPOINTMENT INNER JOIN PATIENT
   ON APPOINTMENT.PT_NO = PATIENT.PT_NO
   INNER JOIN DOCTOR
   ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE APPOINTMENT.MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD