with A as (
    select  MAX(LENGTH) LENGTH, FISH_TYPE
    from FISH_INFO 
    group by FISH_TYPE
)

-- 코드를 작성해주세요
select ID, FISH_NAME, A.LENGTH
from FISH_NAME_INFO INNER JOIN FISH_INFO 
    ON FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
INNER JOIN A
WHERE FISH_INFO.LENGTH = A.LENGTH AND FISH_INFO.FISH_TYPE = A.FISH_TYPE
order by ID