-- 코드를 작성해주세요
SELECT SUM(SCORE) SCORE, HR_GRADE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE INNER JOIN HR_EMPLOYEES 
ON HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
WHERE YEAR = 2022
GROUP BY HR_GRADE.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1