-- 코드를 작성해주세요
select HR_DEPARTMENT.DEPT_ID, DEPT_NAME_EN, round(avg(SAL), 0) AVG_SAL
from HR_DEPARTMENT inner join HR_EMPLOYEES
on HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
group by HR_DEPARTMENT.DEPT_ID
order by AVG_SAL desc